### ISSUE TITLE
Handle empty result

### ISSUE THREAD

**Issue by cleemansen** [movestore/cargo-agent-python#4]
```
2023-02-07 14:38:10 - output-file change detected! <FileCreatedEvent: event_type=created, src_path='/tmp/output_file', is_directory=False>
2023-02-07 14:38:10 - read movingpandas: TrajectoryCollection with 0 trajectories
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/api.py", line 205, in run
    self.dispatch_events(self.event_queue)
  File "/opt/conda/lib/python3.10/site-packages/watchdog/observers/api.py", line 381, in dispatch_events
    handler.dispatch(event)
  File "/opt/conda/lib/python3.10/site-packages/watchdog/events.py", line 271, in dispatch
    self.on_any_event(event)
  File "/cargo-agent-python/src/cargo_agent_event_handler.py", line 24, in on_any_event
    geopandas = self.moving_pandas_analyzer.convert(movingpandas=movingpandas)
  File "/cargo-agent-python/src/analyzer/moving_pandas_analyzer.py", line 16, in convert
    geopandas = movingpandas.to_point_gdf()
  File "/opt/conda/lib/python3.10/site-packages/movingpandas/trajectory_collection.py", line 124, in to_point_gdf
    return concat(gdfs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/opt/conda/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by cleemansen** [comment]
done by b0122a23
